source/bids/models.py
from django.conf import settings
from django.urls import reverse
from decimal import Decimal
from django.db import models
from django.core.exceptions import ValidationError
from django.core.mail import send_mail,send_mass_mail
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from rest_framework.reverse import reverse as api_reverse
import datetime
from django.db.models import Max

from auctions.models import Auction

User=settings.AUTH_USER_MODEL

class Bid(models.Model):
	bidder			=models.ForeignKey(User,on_delete=models.CASCADE)
	auction 		=models.ForeignKey(Auction,on_delete=models.CASCADE)
	bid 			=models.DecimalField(max_digits=8,decimal_places=2)
	
	timestamp		=models.DateTimeField(auto_now_add=True)


	def __str__(self,*args,**kwargs):
		return self.auction.name

	def __init__(self, *args, **kwargs):
		super().__init__(*args,**kwargs)

	def get_absolute_url(self):
		return reverse('bid-create', kwargs={'pk': self.auction.pk,'version':self.auction.version})

	def clean(self,*args,**kwargs):
		bids=Bid.objects.filter(auction=self.auction)
		if not bids.exists():
			if self.bid<=self.auction.minprice:	
				raise ValidationError('Please enter bid more than minprice.')
		elif bids.exists():
			max_bid=bids.aggregate(Max('bid'))['bid__max']
			if self.bid<=max_bid:
				raise ValidationError('Please enter bid more than current bid.')

source/bids/forms.py
from django import forms
from .models import Bid
from django.utils import timezone
from django.core.exceptions import ValidationError

class BidCreateForm(forms.ModelForm):
	class Meta:
		model=Bid
		fields=['bid','auction']


	# deadline=forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M:%S'])

	# def clean_deadline(self):
	# 	deadline = self.cleaned_data['deadline']
	# 	if deadline < (timezone.now()+timezone.timedelta(hours=72)):
	# 		raise ValidationError("The duration of the auction has to be at least 72h")

	# def save(self,commit=True):
	# 	auction=super(AuctionCreateForm,self).save(commit=False)
	# 	if commit:
	# 		auction.send_activation_email()
	# 	return auction

source/bids/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render,redirect
from django.db.models import Max
from django.urls import reverse
from django.core.mail import send_mail
from django.http import HttpResponse,HttpResponseRedirect
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.views.generic import View,ListView,DetailView,CreateView,UpdateView
import copy
from django.contrib import messages
from .forms import BidCreateForm
from auctions.models import Auction
from .models import Bid
# Create your views here.
class BidCreateView(CreateView):
	form_class=BidCreateForm
	template_name='bids/bid_create.html'
	queryset=Auction.objects.all()

	def get_context_data(self,*args,**kwargs):
		context=super(BidCreateView,self).get_context_data(*args,**kwargs)
		pk=self.kwargs.get('pk')
		auction=Auction.objects.filter(pk=pk)[0]
		context['auction']=auction
		bids=Bid.objects.filter(auction=auction)
		bid_times=bids.count()
		context['bid_times']=bid_times
		if bids:
			context['current_bid_price']=bids.aggregate(Max('bid'))['bid__max']
			context['current_bid']=bids.filter(bid=context['current_bid_price'])[0]
		return context

	def get_object(self):
		pk=self.kwargs.get('pk')
		obj=Auction.objects.filter(pk=pk)[0]
		self.request.session['version']=obj.version
		return obj

	def get_initial(self):
		initial=super().get_object()
		return {'auction':self.get_object()}

	def form_valid(self,form):
		au=self.get_object()
		instance=form.save(commit=False)
		bids=Bid.objects.filter(auction=au)
		max_bid=bids.aggregate(Max('bid'))['bid__max']


		# op2:soft deadlines
		now=timezone.now()
		deadline=instance.auction.deadline

		if (deadline-now) < timezone.timedelta(minutes=5):
			deadline+=timezone.timedelta(minutes=5)

		if self.kwargs.get('version')!= au.version:
			messages.add_message(self.request,messages.ERROR,'The auction description has been changed, please replace your bid again.')
			return HttpResponseRedirect(reverse('bid-create',kwargs={'pk': au.pk,'version':au.version}))

		elif instance.bid<=max_bid:
			messages.add_message(self.request,messages.ERROR,'A bid has been make before you. Please replace new bid.')
			return HttpResponseRedirect(reverse('bid-create',kwargs={'pk': au.pk,'version':au.version}))
			
		else:
			instance.bidder=self.request.user
			instance.auction=self.get_object()
			instance.save()

			bids=Bid.objects.filter(auction=instance.auction)
			other_bidders_email=[instance.bidder.email]
			for x in bids:
				other_bidders_email.append(x.bidder.email)		

			subject='New bid registered on YAAS'		
			path_=reverse('bid-create',kwargs={'pk': instance.auction.id,'version':instance.auction.version})
			message=f'A new bid has beed registered on {instance.auction.name}'
			# recipient_list=other_bidders_email
			recipient_list=['yuangao890@gmail.com']
			send_mail(
					subject,
					message,
					'yuangao890@gmail.com',
					recipient_list,
					fail_silently=False, 
					html_message=f'<p>Hi, a new bid has beed registered on <b>{instance.auction.name}</b></p><p>http://127.0.0.1:8000{path_}</p>'
				)			
		
			return super(BidCreateView,self).form_valid(form)


class MyBidListView(LoginRequiredMixin,ListView):
	template_name='bids/my_bids_list.html'
	def get_queryset(self):
		bids=Bid.objects.filter(bidder=self.request.user)
		return bids

source/bids/templates/bids/bid_create.html
{% extends 'base.html' %}
{% load static %}

{% block head_title %}YAAS{% endblock %}

{% block content %}
<h1>{{ auction.name }}{% if auction.banned %}<small> [banned]</small>{% endif %}</h1>
<p>Description: {{ auction.description }}</p>
<p>Starting Bid: {{ auction.minprice }} €</p>
<p>Deadline: {{ auction.deadline }}</p>
<p>Time Left: {{ auction.deadline|timeuntil }}</p>
{% if current_bid %}
<p>Current Bidder: {{ current_bid.bidder}}</p>
{% endif %}

<!-- <p><b>Bid_times: {{ object.bid_times }}</b></p> -->
<h3>Current_bid: 
	<span id='current_bid'>
		{% if current_bid_price %}
		{{ current_bid_price }}
		{% elif not current_bid_price %}
		{{ auction.minprice }}
		{% endif %}

	</span> €  
	<small>[ {{ bid_times }} bids] </small></h3>
<p>Approximately <b>USD $ <span id='usd'></span></b></p>
<p>Approximately <b>CNY ¥ <span id='cny'></span></b></p>

<hr>
<div class='container'>
	{% if request.user.username != auction.seller.username and auction.activated %}
	<div class='col-sm-6'>
		<form class='form' method='POST' action=".">{% csrf_token %}
			{% if messages %}
			<ul class="messages">
			    {% for message in messages %}
			    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			    {% endfor %}
			</ul>
			{% endif %}
			
			{{ form.non_field_errors }}
			<p hidden>
				<label for='id_auction'></label>
				{{form.auction}}
			</p>
			<p>
				<label for='id_bid'></label>
				{{form.bid}}
				<button class='btn btn-primary' type='submit'>Place Bid</button>
			</p>			
			<p>Enter bid more than current bid.</p> 
			
		</form>
	</div>
	{% endif %}

	{% if request.user.is_superuser %}
		{% if auction.activated %}
		<div class='col-sm-6'>		
			<form 
				class='form' 
				method='POST' 
				action="{% url 'auction-ban' pk=auction.pk %}"
				onsubmit="return confirm('Are you sure to ban this Auction?')"
				>{% csrf_token %}
				<p>The auction does not comply with the usage terms of this site.</p>
				<button class='btn btn-danger' type='submit'>Ban</button>
			</form>			
		</div>
		{% endif %}	
	{% endif %}

{% endblock %}

source/bids/templates/bids/my_bids_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block head_title %}YAAS{% endblock %}

{% block content %}
<div>
	<h2>{% trans 'MyBids' %}</h2>
	{% for obj in object_list %}
	<li><a href="{% url 'bid-create' pk=obj.auction.pk version=obj.auction.version %}">{{ obj.auction.name }}</a></li>
	{% endfor %}
</div>
{% endblock %}