source/auctions/api/urls.py
from django.urls import path,include,re_path
from .views import AuctionListAPIView,BidCreateAPIView
app_name = 'auctions'

urlpatterns = [
    path('auctions/', AuctionListAPIView.as_view(),name='api-auction-list'),
    path('bids/', BidCreateAPIView.as_view(),name='api-bid-create'),
    # re_path(r'^(?P<pk>\d+)$', BidCreateAPIView.as_view(),name='api-bid-create'),
]

source/auctions/models.py
from django.conf import settings
from django.urls import reverse
from decimal import Decimal
from django.db import models
from django.core.exceptions import ValidationError
from django.core.mail import send_mail,send_mass_mail
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from rest_framework.reverse import reverse as api_reverse
import datetime
from .utils import code_generator

User=settings.AUTH_USER_MODEL

class Auction(models.Model):
	seller 			=models.ForeignKey(User,on_delete=models.CASCADE)
	name 			=models.CharField(max_length=120)
	description 	=models.TextField(null=True,blank=True)
	minprice		=models.DecimalField(max_digits=8,decimal_places=2)
	deadline	 	=models.DateTimeField(auto_now=False)
	

	timestamp		=models.DateTimeField(auto_now_add=True)
	updated			=models.DateTimeField(auto_now=True)

	version 		=models.IntegerField(default=0)

	activation_key 	=models.CharField(max_length=120,blank=True,null=True)
	activated 		=models.BooleanField(default=False)
	banned			=models.BooleanField(default=False)
	due				=models.BooleanField(default=False)
	adjudicated		=models.BooleanField(default=False)


	def __str__(self,*args,**kwargs):
		return self.name

	def get_absolute_url(self):
		return reverse('my-auctions-detail-update', kwargs={'pk': self.pk})

	def send_activation_email(self):
		if not self.activated:
			self.activation_key=code_generator()
			self.save()
			print(self.pk)
			path_=reverse('activate-auction',kwargs={'code':self.activation_key})
			path1_=reverse('my-auctions-detail-update',kwargs={'pk': self.pk})
			subject = 'Activate Auction'
			from_email = settings.DEFAULT_FROM_EMAIL
			message = f'Activate your auction here:{path_}'
			recipient_list =['yuangao890@gmail.com'] 
			# recipient_list =[self.user.email] 
			html_message = f'<p>Activate your auction here:  http://127.0.0.1:8000{path_}</p><p>Check your created auction here: http://127.0.0.1:8000{path1_}</p>'
			print(html_message)

			# task_mail.delay(self.activation_key,self.pk)
	# 		
			sent_email=send_mail(
				subject,
				message,
				'yuangao890@gmail.com',
				recipient_list,
				fail_silently=False, 
				html_message=html_message
			)
			return sent_email


		def save(self, *args, **kwargs):
			now=timezone.now().strftime("%Y-%m-%d %H:%M:%S")
			deadline=self.deadline
				
			if type(self.deadline) is datetime.datetime:
				deadline=self.deadline.strftime("%Y-%m-%d %H:%M:%S")

			if self.activated and deadline < now:
				self.due=True
				self.activated=False


			if self.due and not self.adjudicated:
				other_bidders_email=[self.seller.email]
				# for x in self.bidders.all():
				# 	other_bidders_email.append(x.email)

				subject='A winner has beed selected!'		
				path_=reverse('make-bid',kwargs={'pk':self.pk,'version':self.version})
				message=f'{self.name} got a winner. '

				subject1='Congratulations! You win an auction on YAAS!'		
				path1_=reverse('make-bid',kwargs={'pk':self.pk,'version':self.version})
				message1=f'You are the winner of {self.name}. Check on http://127.0.0.1:8000{path1_}'

				subject2='A winner has beed selected!'		
				path2_=reverse('make-bid',kwargs={'pk':self.pk,'version':self.version})
				message2=f'{self.name} got a winner. Check on http://127.0.0.1:8000{path2_}'
				# recipient_list=other_bidders_email
				recipient_list=['yuangao890@gmail.com']

				datatuple=(
						(subject1,message1,'yuangao890@gmail.com',recipient_list),
						(subject2,message2,'yuangao890@gmail.com',recipient_list),	
					)
				send_mass_mail(
					datatuple,
					fail_silently=False
					)
				self.adjudicated=True

source/auctions/forms.py
from django import forms
from .models import Auction
from django.utils import timezone
from django.core.exceptions import ValidationError

class AuctionCreateForm(forms.ModelForm):
	class Meta:
		model=Auction
		fields=['name','description','minprice']

	deadline=forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M:%S'])

	def clean_deadline(self):
		deadline = self.cleaned_data['deadline']
		if deadline < (timezone.now()+timezone.timedelta(hours=72)):
			raise ValidationError("The duration of the auction has to be at least 72h")

	def save(self,commit=True):
		auction=super(AuctionCreateForm,self).save(commit=False)
		if commit:
			auction.send_activation_email()
		return auction

class AuctionUpdateForm(forms.ModelForm):
	class Meta:
		model=Auction
		fields=['description']

source/auctions/templates/auctions/auction_banned_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block head_title %}YAAS{% endblock %}

{% block content %}
<h1>{% trans 'Banned Auctions' %}</h1>
{% for obj in object_list %}
<li>{{ obj.name }}[ Banned ]</li>
{% endfor %}
{% endblock %}

source/auctions/templates/auctions/auction_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block head_title %}YAAS{% endblock %}

{% block content %}
<div>	
	<form class='form' method='GET' action='.'>
		<input type='text' placeholder="Search.." name='q' value='{{ request.GET.q }}'>
		<button class='btn btn-default' type='submit'>{% trans 'Search' %}</button>
	</form>

	{% for obj in object_list %}
		{% if obj.activated %}
		<li><a href="{% url 'bid-create' pk=obj.pk  version=obj.version %}">{{ obj.name }}</a>
		<!-- <p>{{obj.description}}</p> -->
		</li>
		{% endif %}
	{% endfor %}
	<p class='just_test'>just_test</p>
</div>
{% endblock %}

source/auctions/templates/auctions/my_auction_create.html
{% extends 'base.html' %}
{% load i18n %}
{% block head_title %}YAAS{% endblock %}

{% block content %}
<h1>{% trans 'CreateAuction' %}</h1>
<form method='POST' action="" onsubmit="return">{% csrf_token %}
    {{ form.as_p }}
    <!-- {{ form.non_field_errors }} -->
    <!-- <p>
    	<label for='id_name'>Title: </label>
    	<input type='text' name='name' required id='id_name'>
    </p>
    <p>
    	<label for='id_description'>Description:</label>
    	<textarea  name='description' cols='40' rows='10' id='id_description'></textarea>
    </p>
    <p>
    	<label for='id_minprice'>Minprice:</label>
    	<input type='number' name='minprice' step='0.01' required id='id_minprice'>
    </p>
    <p>
    	<label for='id_deadline'>Deadline:</label>
    	<input type='time' name='deadline' required id='id_deadline'>
    </p> -->
    <p>eg: 2018-01-25 14:30:59</p>
    <button type='submit' class='btn btn-primary'>{% trans 'Save' %}</button>
</form>
<p>{% trans 'After save the auction, please go to your email to confirm to activate this auction.' %}</p>
{% endblock %}

source/auctions/templates/auctions/my_auction_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block head_title %}YAAS{% endblock %}

{% block content %}
<h1>{% trans 'MyAuctions' %}  
	<a href="{% url 'auction-create' %}">
		<small>{% trans 'CreateAuction' %}</small>
	</a>
</h1>

{% for obj in object_list %}
	<!-- {% if not obj.activated and not obj.banned and not obj.due and not adjudicated %}  -->
	<li><a href="{% url 'my-auctions-detail-update' pk=obj.pk %}">{{ obj.name }} [Inactivated]</a></li>
	<!-- {% endif %} -->

	{% if obj.banned  %} 
	<li>
		<a href="{% url 'my-auctions-detail-update' pk=obj.pk %}">{{ obj.name }} [banned]</a>
	</li>
	{% endif %}

	{% if obj.due  %} 
	<li>
		<a href="{% url 'my-auctions-detail-update' pk=obj.pk %}">{{ obj.name }} [due]</a>
	</li>
	{% endif %}

	{% if obj.adjudicated  %} 
	<li>
		<a href="{% url 'my-auctions-detail-update' pk=obj.pk %}">{{ obj.name }} [adjudicated]</a>
	</li>
	{% endif %}

	{% if obj.activated %}  
	<li>
		<a href="{% url 'my-auctions-detail-update' pk=obj.pk %}">{{ obj.name }}</a>
	</li>
	{% endif %}
{% endfor %}
{% endblock %}

source/auctions/templates/auctions/my_auction_update.html
{% extends 'base.html' %}
{% load i18n %}
{% block head_title %}YAAS{% endblock %}

{% block content %}
<h1>{{ object.name }}</h1>
<p>{% trans 'Description' %}: {{ object.description }}</p>
<p>{% trans 'Starting Bid' %}: {{ object.minprice }}</p>
<p>{% trans 'Bid Times' %}: {{ object.bid_times }}</p>
<p>{% trans 'Deadline' %}: {{ object.deadline }}</p>

<hr> 
<h2>{% trans 'Update Auction Description' %}</h2>
<form method='POST' action="" > {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>{% trans 'Update' %}</button>
</form>
<br/>
<p>{% trans 'Last Updated' %}: {{ object.updated }}</p>
{% endblock %}